#!/usr/bin/env bash
# displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
list=$(ls)
for content in $list
do
 echo "$content" | cut -d '-' -f2
done
